name: CI/CD

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack ./src/ColorSupport/ColorSupport.csproj -c release -o ./dist
    - name: push
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        NUGET_API_KEY: ${{ secrets.NugetApiKey }}
      run: cd nuget && dotnet nuget push "dist/*.nupkg" --api-key "$NUGET_API_KEY"